[package]
name = "miro"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
clap = {version = "4.5.32", features = ["derive"] }
iced = {version = "0.13.1", features = ["image"] }
iced_aw = { version = "0.12.2", default-features = false, features = ["menu"] }
iced_native = "0.10.3"
mupdf = "0.4.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
