name: CI

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 500
      - uses: dtolnay/rust-toolchain@stable
      - run: sudo apt-get -y install libfontconfig1-dev
      - run: cargo clippy --tests --features serde -- -D warnings

  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2019]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 500
      - uses: dtolnay/rust-toolchain@stable
      - run: sudo apt-get -y install libfontconfig1-dev
        if: matrix.os == 'ubuntu-latest'
      - name: Install LLVM
        if: matrix.os == 'windows-2019'
        run: choco install -y llvm
      - name: Setup msbuild
        if: matrix.os == 'windows-2019'
        uses: microsoft/setup-msbuild@v1.3.1
      - run: cargo build --release
        timeout-minutes: 20
        if: matrix.os == 'windows-2019'
        env:
          LIBCLANG_PATH: "C:\\Program Files\\LLVM\\bin"
      - run: cargo build --release
        if: matrix.os != 'windows-2019'

        # --- START: Step to create release and upload binary ---
      - name: Create Release
        # This step runs only for the ubuntu-latest matrix entry
        if: |
          startsWith(github.ref, 'refs/tags/') &&
          matrix.os == 'ubuntu-latest' &&
          success() # Only run if previous steps in this job were successful
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/miro # *** Verify this path is correct for your binary ***
          # Optional: Add a release name and body
          # name: YourAppName ${{ github.ref_name }}
          # body: |
          #   Release notes for version ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # --- END: Step to create release and upload binary ---
